source 'https://github.com/zouzijidelu/WZBModuleDemo'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WZBModuleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WZBModuleDemo
    pod 'WZBModuleDemo'
end
